### ISSUE TITLE
How about the other eclipses?

### ISSUE THREAD

**Issue by Krukarius** [gmiller123456/solareclipseviewer#2]
Your map is excellent!
Could be possible to provide the other eclipses? 2026, 2027 if possible?

**Comment by gmiller123456** [comment]
The Besselian Elements for other eclipses +-2000 years is here: https://github.com/gmiller123456/FiveMillenniumCanonOfSolarEclipses-Besselian-Elements

You can plug those in to the values at the beginning of eclipse.js.  I didn't provide the option of selecting them, as the map tends to get confused when paths cross the poles or the International Date Line.  I do plan to eventually fix that issue and allow the selection of any eclipse, but don't have an ETA.
